"""
SHAP Explainability View — FED-GBM V3 Dashboard.

Displays SHAP global feature importance and per-patient waterfall charts
generated by run_improved_experiments or cgga_experiment_b with plain-language explanations.
"""

import os
import glob
import streamlit as st
import pandas as pd

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))

SHAP_DIRS = [
    os.path.join(_ROOT, "results", "improved_experiments", "shap"),
    os.path.join(_ROOT, "experiments", "results", "improved_experiments", "shap"),
    os.path.join(_ROOT, "results", "v3", "improved_experiments", "shap"),
    os.path.join(_ROOT, "results", "archive", "experiment_b", "shap"),
    os.path.join(_ROOT, "results", "v3", "experiment_b", "shap"),
    os.path.join(_ROOT, "scratch"),
]


def _find_shap_files(pattern: str) -> list:
    results = []
    for d in SHAP_DIRS:
        if os.path.isdir(d):
            results.extend(glob.glob(os.path.join(d, pattern)))
    return sorted(results)


def render():
    st.markdown("""
    <div style="padding:10px 0 16px;">
        <div style="font-size:24px;font-weight:700;color:#0f172a;font-family:'Inter',sans-serif;">
            🔍 Feature Importance & Patient Insights (SHAP)
        </div>
        <div style="font-size:14px;color:#475569;margin-top:4px;">
            Explaining which clinical factors drive brain tumor survival predictions for the whole group and for individual patients.
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Easy Language Explanation Banner
    st.info(
        "💡 **How to Understand SHAP Model Explanations (Easy Language):**\n\n"
        "- **SHAP (SHapley Additive exPlanations):** Measures how much each health factor (like Age, Chemotherapy, or Radiation) pushes the predicted survival probability up or down.\n"
        "- **Global Bar Plot:** Shows which features matter most overall (the longest bar = most important factor).\n"
        "- **Beeswarm Plot:** Shows whether high feature values (red dots) or low values (blue dots) improve or hurt survival.\n"
        "- **Patient Waterfall Chart:** Shows a personalized breakdown of one specific patient's risk factors.",
        icon="ℹ️"
    )

    summary_bars = _find_shap_files("shap_summary_*_bar.png")
    summary_bees = _find_shap_files("shap_summary_*_beeswarm.png")
    waterfalls = _find_shap_files("shap_waterfall_*.png")
    importance_csvs = _find_shap_files("shap_importance_*.csv")

    if not summary_bars and not summary_bees:
        st.warning(
            "🔄 SHAP analysis plots not yet generated on disk. Run `python -m src.fed_gbm.run_improved_experiments` "
            "from the project root to compute SHAP values.",
            icon="⚠️"
        )
        return

    # ---- Global importance CSV table ----
    if importance_csvs:
        st.markdown("### 📊 Global Feature Importance Ranking")
        dfs = []
        for csv_path in importance_csvs:
            df_tmp = pd.read_csv(csv_path)
            df_tmp["source"] = os.path.basename(csv_path)
            dfs.append(df_tmp)
        df_imp = pd.concat(dfs).groupby("feature")["mean_abs_shap"].mean().reset_index()
        df_imp = df_imp.sort_values("mean_abs_shap", ascending=False).reset_index(drop=True)
        df_imp.columns = ["Feature", "Mean |SHAP| Impact"]
        df_imp["Rank"] = range(1, len(df_imp) + 1)

        col1, col2 = st.columns([1, 2])
        with col1:
            st.dataframe(df_imp[["Rank", "Feature", "Mean |SHAP| Impact"]].round(4), hide_index=True, use_container_width=True)
        with col2:
            st.bar_chart(df_imp.set_index("Feature")["Mean |SHAP| Impact"])

        st.markdown(
            """
            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin:10px 0 20px;font-size:13px;color:#334155;">
                <b>💡 Feature Ranking Interpretation:</b> The table and chart show the top clinical & molecular factors driving survival predictions.
                Molecular biomarkers (IDH1 mutation & MGMT promoter methylation), Karnofsky Performance Status (KPS), treatment regimen (Radiation & Chemotherapy), and patient Age are the primary drivers of 12-month glioblastoma survival.
            </div>
            """,
            unsafe_allow_html=True
        )

    # ---- Summary plots ----
    st.markdown("### 📈 SHAP Overview Summary Plots")
    tab1, tab2 = st.tabs(["Bar Plot (Overall Ranking)", "Beeswarm Plot (Feature Impact Direction)"])

    with tab1:
        if summary_bars:
            cols = st.columns(min(len(summary_bars), 2))
            for i, img in enumerate(summary_bars[:4]):
                name = os.path.basename(img).replace("shap_summary_", "").replace("_bar.png", "").replace("_", " ")
                cols[i % 2].image(img, caption=f"Overall Feature Importance: {name}", use_column_width=True)
            st.markdown(
                """
                <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin-top:10px;font-size:13px;color:#334155;">
                    <b>💡 Bar Plot Interpretation (Easy Language):</b> Longer bars mean the feature has a bigger overall impact on patient predictions across the dataset.
                </div>
                """,
                unsafe_allow_html=True
            )
        else:
            st.info("Bar plots pending generation.")

    with tab2:
        if summary_bees:
            cols = st.columns(min(len(summary_bees), 2))
            for i, img in enumerate(summary_bees[:4]):
                name = os.path.basename(img).replace("shap_summary_", "").replace("_beeswarm.png", "").replace("_", " ")
                cols[i % 2].image(img, caption=f"Impact Direction: {name}", use_column_width=True)
            st.markdown(
                """
                <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin-top:10px;font-size:13px;color:#334155;">
                    <b>💡 Beeswarm Plot Interpretation (Easy Language):</b> Each dot represents one patient.
                    Red dots mean high feature values (e.g. receiving treatment), while blue dots mean low feature values.
                    Dots to the right of the center line increase predicted survival probability; dots to the left decrease it.
                </div>
                """,
                unsafe_allow_html=True
            )
        else:
            st.info("Beeswarm plots pending generation.")

    # ---- Per-patient waterfalls ----
    if waterfalls:
        st.markdown("---")
        st.markdown("### 👤 Single Patient Risk Breakdown (Waterfall Charts)")
        st.caption(f"{len(waterfalls)} patient-level explanations available")

        patients = [os.path.basename(w).replace("shap_waterfall_", "").replace(".png", "") for w in waterfalls]
        selected = st.selectbox("Select Patient Case", patients)
        selected_path = next((w for w in waterfalls if selected in w), None)
        if selected_path:
            st.image(selected_path, caption=f"SHAP Personalized Breakdown — {selected}", use_column_width=True)
            st.markdown(
                f"""
                <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin-top:10px;font-size:13px;color:#334155;">
                    <b>💡 Patient Waterfall Interpretation ({selected}):</b><br>
                    This chart explains how the model made its decision for <b>{selected}</b>.
                    Red bars show factors that increased this patient's predicted survival, while blue bars show factors that decreased their predicted survival.
                </div>
                """,
                unsafe_allow_html=True
            )

    # ---- Clinical context metrics ----
    st.markdown("---")
    st.markdown("### 🩺 Clinical Factor Key Insights")
    cols = st.columns(3)
    with cols[0]:
        st.metric("Age", "Older → Higher Risk", help="Older patients have lower baseline overall survival rate")
    with cols[1]:
        st.metric("Treatment Radiation", "Radiation → Lower Risk", help="Standard of care radiotherapy improves survival")
    with cols[2]:
        st.metric("Treatment Chemo", "Temozolomide → Lower Risk", help="Chemotherapy prolongs median survival time")
